package com.bookstore.controller;
import com.bookstore.entity.*; import com.bookstore.service.*; import jakarta.validation.Valid; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*;
@Controller public class WebController {private final BookService books; private final UserService users; private final CartService cart; private final OrderService orders; private final ReviewService reviews; private final MailNotificationService mail;
 public WebController(BookService b,UserService u,CartService c,OrderService o,ReviewService r,MailNotificationService m){books=b;users=u;cart=c;orders=o;reviews=r;mail=m;}
 private User me(Authentication a){return users.find(a.getName());}
 @GetMapping("/") public String home(Model m,@RequestParam(required=false)String q,@RequestParam(required=false)String category){m.addAttribute("books",books.all(q,category));m.addAttribute("q",q);return "home";}
 @GetMapping("/login") public String login(){return "login";} @GetMapping("/register") public String register(){return "register";}
 @PostMapping("/register") public String registerPost(@RequestParam String username,@RequestParam String password,@RequestParam String email){users.register(username,password,email);return "redirect:/login?registered";}
 @GetMapping("/books/new") public String newBook(Model m){m.addAttribute("book",new Book());return "book-form";} @PostMapping("/books/save") public String save(@Valid @ModelAttribute Book b){books.save(b);return "redirect:/";} @GetMapping("/books/edit/{id}") public String edit(@PathVariable Long id,Model m){m.addAttribute("book",books.get(id));return "book-form";} @PostMapping("/books/delete/{id}") public String delete(@PathVariable Long id){books.delete(id);return "redirect:/";}
 @GetMapping("/books/{id}") public String detail(@PathVariable Long id,Model m){m.addAttribute("book",books.get(id));m.addAttribute("reviews",reviews.forBook(id));return "book-detail";}
 @PostMapping("/books/{id}/review") public String review(@PathVariable Long id,Authentication a,@RequestParam int rating,@RequestParam String comment){reviews.add(me(a),id,rating,comment);return "redirect:/books/"+id;}
 @PostMapping("/cart/add/{id}") public String addCart(@PathVariable Long id,@RequestParam(defaultValue="1")int quantity,Authentication a){cart.add(me(a),id,quantity);return "redirect:/cart";} @GetMapping("/cart") public String cart(Authentication a,Model m){m.addAttribute("items",cart.items(me(a)));m.addAttribute("total",cart.total(me(a)));return "cart";} @PostMapping("/cart/remove/{id}") public String removeCart(@PathVariable Long id){cart.remove(id);return "redirect:/cart";}
 @GetMapping("/checkout") public String checkout(Authentication a,Model m){m.addAttribute("total",cart.total(me(a)));return "checkout";} @PostMapping("/checkout") public String checkoutPost(Authentication a,@RequestParam String address,@RequestParam String payment){Order o=orders.checkout(me(a),address,payment);mail.orderPlaced(o);return "redirect:/orders";} @GetMapping("/orders") public String orders(Authentication a,Model m){m.addAttribute("orders",orders.mine(me(a)));return "orders";}
 @PostMapping("/admin/users/{id}/role") public String role(@PathVariable Long id,@RequestParam Role role){ users.setRole(id,role); return "redirect:/admin";} @GetMapping("/admin") public String admin(Model m){m.addAttribute("bookCount",books.count());m.addAttribute("userCount",users.count());m.addAttribute("orderCount",orders.count());m.addAttribute("lowStock",books.lowStock());m.addAttribute("orders",orders.all());m.addAttribute("users",users.all());return "admin";} @PostMapping("/admin/orders/{id}/status") public String status(@PathVariable Long id,@RequestParam OrderStatus status){orders.status(id,status);return "redirect:/admin";}
}
